Add isprime
HTSTEM/discord-bot pull request #22
Opened 2017-10-03 05:28 UTC by spdskatr

2017-10-03 08:40 UTC, spdskatr commented
oops

2017-10-03 16:55 UTC, Bottersnike requested changes
Other than these, it looks pretty good.

2017-10-03 16:55 UTC, Bottersnike commented on config.example.yml
> +  - google
Can we have the newline back or was it crashing things?

2017-10-03 16:55 UTC, Bottersnike commented on cogs/misc.py
> +        return await ctx.send('Prime! {} is only divisible by 1 and itself'.format(num))
Maybe a `.` or `!` at the end of this message?

2017-10-03 16:55 UTC, Bottersnike commented on cogs/misc.py
> +from math import sqrt
`import math` then `math.sqrt` to avoid polluting the namespace?

2017-10-03 16:55 UTC, Bottersnike commented on cogs/misc.py
> +        if num >= 1000000:
A _bit_ pedantic, but `>=` is redundant here as `==` is caught by `num % 5` earlier in the code. (Just use `>`)

2017-10-03 17:17 UTC, ZweiSpeedruns commented
There are only about 70,000 primes in this range, so a lookup table is kinda feasable. The primality checking in general is pretty crappy, has anyone actually tested to see how long it would take for noah's computer to check 999,983?

My proposal: make a lookup table for the first ~10,000 primes and have larger numbers be checked against those **and only those** up to sqrt(n).

2017-10-03 17:25 UTC, Bottersnike commented
On mediocre hardware, `10**10` will execute in around `0.3175048660126221` seconds. Upping it to `10**11` will take it to `1.0105299202432678`s, but I think `10**6` is probably a bit too small as that can easily execute in `0.0027852597500475137`s

2017-10-03 17:29 UTC, ZweiSpeedruns commented
Botter, do you actually understand how primes work?

Those numbers are basically best case scenarios. They get caught in the fist n%2 check and get passed. This is why I suggested  999983 as a test case, as it's worse case (and more representative of larger numbers)

2017-10-03 17:29 UTC, Bottersnike commented
Heh.. Derp..

2017-10-03 17:33 UTC, Bottersnike commented
`999983` still had an average of `0.0009293756430673246` seconds

2017-10-03 18:47 UTC, ZweiSpeedruns commented
I forget how fast modern computers are, I suppose we could go to 10**7 but I'd rather stay in the range of integers.

2017-10-04 08:20 UTC, spdskatr reviewed
All good, 1 million was just an arbitrary limit for the time being. I'll change it

2017-10-04 10:07 UTC, spdskatr commented
After a bit of testing the prime number 1000000005721 yielded 0.47870827575113567 seconds

2017-10-12 05:39 UTC, spdskatr commented
made changes

2017-10-12 05:41 UTC, merged